Django/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     url(r'^posts/', include('posts.urls', namespace="posts")),
#     url(r'^comments/', include('django_comments.urls')),
#     url(r'^api/', include('api.urls', namespace="api")),


    
# ]
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace="posts")),
    url(r'^api/', include('api.urls', namespace="api")),
    url(r'^comments/', include('django_comments.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
# from django.conf.urls import url
# from .views import PostListAPIView ,PostDetailAPIView,PostDeleteAPIView,PostCreateAPIView


# urlpatterns = [
#     url(r'^list/$', PostListAPIView.as_view(), name="list"),
#     url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
#     url(r'^detail/(?P<post_slug>[-\w]+)/$', PostDetailAPIView.as_view(), name="detail"),
#     url(r'^delete/(?P<post_slug>[-\w]+)/$', PostDeleteAPIView.as_view(), name="delete"),
    
# ]

from django.conf.urls import url
from api.views import *


urlpatterns = [
    url(r'^list/$', PostListAPIView.as_view(), name="list"),
    url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
    url(r'^detail/(?P<post_slug>[-\w]+)/$', PostDetailAPIView.as_view(), name="detail"),
    url(r'^delete/(?P<post_slug>[-\w]+)/$', PostDeleteAPIView.as_view(), name="delete"),
    url(r'^comment/list/$', CommentListAPIView.as_view(), name="comment_list"),
	url(r'^comment/create/$', CommentCreateAPIView.as_view(), name="comment_create"),
	url(r'^register/$', UserCreateAPIView.as_view(), name="register"),
	url(r'^login/$', UserLoginAPIView.as_view(), name="login"),

]

posts/urls.py
from django.conf.urls import url
from . import views 

urlpatterns = [
    url(r'^detail/(?P<slug>[-\w]+)/$', views.post_detail, name = "detail"),
    url(r'^update/(?P<slug>[-\w]+)/$', views.post_update, name = "update"),
    url(r'^delete/(?P<slug>[-\w]+)/$', views.post_delete, name = "delete"),
    url(r'^list/$' ,views.post_list, name = "list"),
    url(r'^create/$' ,views.post_create, name = "create"),
    url(r'^signup/$' ,views.usersignup, name = "signup"),
    url(r'^login/$' ,views.user_login, name = "login"),
    url(r'^logout/$' ,views.userlogout, name = "logout"),
    url(r'^like_button/(?P<post_id>[\d]+)/$', views.like_button, name = "like_button"),


    
]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
	author = models.ForeignKey(User,default=1)
	title = models.CharField(max_length=50)
	image = models.ImageField(null=True , blank=True,upload_to="Django_images") 
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField()
	updated = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	slug = models.SlugField(unique=True , null=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"slug": self.slug})



	class Meta:
		ordering =['-timestamp' ,'-updated']

#def create_slug(instance,new_slug=None):
	#slug=slugify(instance.title)
	#if new_slug is not None:
	#	slug =new_slug
	#qs =Post.objects.filter(slug=slug).order_by("id")
	#exists =qs.exists()
	#if exists:
			#new_slug="%s-%s"(slug,qs.first().id)
			#return create_slug(instance,new_slug=new_slug)
	#return slug

def post_reciever(sender,instance,*args,**kwargs):
	if not instance.slug:
		slug =slugify(instance.title)
		qs=Post.objects.filter(slug=slug).order_by("-id")
		exists=qs.exists()
		if exists:
			slug ="%s-%s"%(slug,instance.id)
		instance.slug=slug
		instance.save()

		

post_save.connect(post_reciever , sender=Post)


class Like(models.Model):
	user =models.ForeignKey(User)
	post =models.ForeignKey(Post)

posts/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User 

class PostForm(forms.ModelForm):
	class Meta:
		model = Post 
		fields =['title','content' , 'image','draft','publish']
		
		widgets = {
		'publish':forms.DateInput(attrs={"type":"date"}),
		}



class UserSignUp(forms.ModelForm):

	class Meta :
		model= User 

		fields = ['username','password']

		widgets ={

		'password':forms.PasswordInput()
		}

class UserLogin(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True , widget=forms.PasswordInput())

posts/views.py
from django.shortcuts import render , redirect
from .models import *
from django.shortcuts import get_object_or_404
from .forms import PostForm ,UserSignUp ,UserLogin
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib.parse import quote
from django.http import Http404 , JsonResponse
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth import authenticate,login ,logout
# Create your views here.
"""def post_create(request):
	post_list = Post.objects.all()
	post_filter = Post.objects.filter(title='Noor')
	post_get = Post.objects.get(title = "gf")
	context={
	"user": request.user,
	"list": post_list,
	"filter": post_filter,
	get": post_get

	#"random_number":random.re
	
	}
	 return render(request,'create.html',context) """

def like_button(request,post_id):
	obj=Post.objects.get(id=post_id)

	like, created = Like.objects.get_or_create(user=request.user , post=obj)

	if created:
		action="like"
	else:
		action="unlike"
		like.delete()
	post_like_count = obj.like_set.all().count()


	context ={

		"action":action,
		"like_count":post_like_count,

	}


	return JsonResponse(context, safe=False)
def usersignup(request):
	context ={}
	form = UserSignUp()
	context['form']=form
	if request.method == "POST":
		form = UserSignUp(request.POST)
		if form.is_valid():

			user = form.save(commit=False)
			username = user.username
			password = user.password
			user.set_password(password)
			user.save()
			auth_user = authenticate(username=username,password=password)
			login(request,auth_user)
			

			return redirect("posts:list")
		messages.error(request,form.errors)
		return redirect("posts:signup")
	return render(request,'signup.html', context)

def post_detail(request ,slug):
	obj=get_object_or_404(Post, slug=slug)
	date =timezone.now().date()

	if obj.publish > date or obj.draft:
		if not request.user.is_staff or request.user.is_superuser:
			raise Http404
	if request.user.is_authenticated():
		if Like.objects.filter(post=obj,user=request.user).exists():
			like=True 
		else :
			like = False
	post_like_count = obj.like_set.all().count()

	user_like_count = request.user.like_set.all().count()
	context ={
	"object":obj,
	}
	return render(request,'post_detail.html',context)
def user_login(request):

	context ={}
	form = UserLogin()
	context['form']=form
	if request.method == "POST":
		form = UserLogin(request.POST)
		if form.is_valid():
			username=form.cleaned_data['username']
			password=form.cleaned_data['password']

			auth_user = authenticate(username=username,password=password)
			login(request,auth_user)
			return redirect("posts:list")
			messages.error(request,"Wrong username/password combination. Please try again.")
			print ("--------------")
			print(author_user)
			print ("--------------")
			return redirect("posts:login")
			messages.error(request,form.errors)
			return redirect("posts:login")

		
	return render(request,'login.html', context)

def userlogout(request):
	logout(request)
	return redirect("posts:login")

def post_list(request):
	today = timezone.now().date()

	if request.user.is_staff or request.user.is_superuser:
		obj_list = Post.objects.all()
	else:
		obj_list = Post.objects.filter(draft=False).filter(publish__lte=today)


	query = request.GET.get("q")
	if query:
		obj_list=obj_list.filter(
			Q(title__icontains=query)|
			Q(content__icontains=query)|
			Q(author__first_name__icontains=query)|
			Q(author__last_name__icontains=query)
			).distinct()

	paginator = Paginator(obj_list, 4) # Show 5 contacts per page
	page = request.GET.get('page')
	try:
		obj = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		obj = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		obj = paginator.page(paginator.num_pages)
	context = {
	"post_list": obj,
	
	"today": today,
	}
	return render(request, 'post_list.html', context)
def post_create(request):

	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	form = PostForm(request.POST or None , request.FILES or None)
	if form.is_valid():
		obj =form.save(commit=False)
		obj.author = request.user
		obj.save()
		messages.success(request,"OMG! So Cool!")
		return redirect ("posts:list")
	context = {
		"form":form
	}
	return render(request,'post_create.html',context)


def post_update(request,slug):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404
	post_object = get_object_or_404(Post , slug=slug)
	form = PostForm(request.POST or None , request.FILES or None ,instance=post_object)
	if form.is_valid():
		form.save()
		#messages.success(request,"Giving it a second thought?")
		return redirect ("posts:list")
	context = {
		"form":form,
		"post_object":post_object,
	}
	return render(request,'post_update.html',context)

def post_delete(request, slug):
	if not (request.user.is_superuser):
		raise Http404
	Post.objects.get(slug=slug).delete()
	messages.warning(request ,"Seriously bro?")
	return redirect ("posts:list")
	

posts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="UTF-8">
	<title>
		{% block head_title %}
		{% endblock head_title %}
	</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet"  href="{% static 'css/base.css' %}">

</head>
<body>

{% include "facebook.html" %}
{% include 'navbar.html' %}
{% include 'messages.html' %}

<div class="container">
{% block content %}

{% endblock content %}
</div>
<script
  src="http://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>





</html>

posts/templates/create.html
<!DOCTYPE html>
<html>
<head>
    
    <title>Create Page</title>

   
</head>
<body>
    
    <h1 >{{user}}</h1>
      <ol> 
    {% for instance in list %}
        <li>{{instance.title}}</li>
        {% endfor %} 
      </ol>
      <ul>
    {% for whatever in filter %}
     
        <li>{{whatever.content}}</li>
        {% endfor %} 
        </ul>
        
     
        <h1>{{get.content}}</h1>
        <h1>{{get.title}}</h1>
        <h1>{{get.timestamp}}</h1>
        <h1>{{get.updated}}</h1>



</body>
</html>

posts/templates/django_comments.html
{% load comments %}
 {% get_comment_list for  object as steve %}




{% for comment in steve %}

     <div class="alert alert-info">{{comments.user_name}} said:{{comment.comment|linebreaks}}
                </div>

{% endfor %}


{% get_comment_form for object as form %}
{% if request.user.is_authenticated %}
 <form action="{% comment_form_target %}" method="POST">

    {% csrf_token %}

    <input type="hidden" name="name" value="{{request.user.username}}">
    <input type="hidden" name="email" value="{{request.user.email}}">
    <textarea type="text" class="form-control input-lg" name="comment"> </textarea>

    {{form.content_type}}
    {{form.object_pk}}
    {{form.timestamp}}
    {{form.security_hash}}

    <input type="hidden" name="next" value="{{object.get_absolute_url}}">


    <input type="submit" name="submit" class="btn btn-primary">
                

</form>
{% else %}
<h3>Please Log in to comment</h3>

{% endif %}

posts/templates/facebook.html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

posts/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}


{% block content %}
  <div class="row">
	<div class="col-sm-6 col-sm-offset-3">
	
	<form method="Post" action="{% url 'posts:login' %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value=" Login " class="btn btn-info">
	
	</form>
		</div>
</div>


{% endblock content %}

posts/templates/messages.html
{% if messages %}
	<ul class ="messages">
		{% for message in messages %}
		<div></div>{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>

		<button type="button" class="close" data-dismiss="alert" aria-label="Close">

			<span aria-hidden="true">&times;</span>
		</button>
  
		{{ message }}
		</div>
		{% endfor %}
	</ul>
	{% endif %}

posts/templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
 


      <form class="navbar-form navbar-left" action ="{% url 'posts:list' %}" method ="GET">
        <div class="form-group">
          <input type="text" name="q" class="form-control" placeholder="Search" value"{{request.GET.q}}" >
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

posts/templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{title}}
{% endblock title %}

	
{% block content %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
	<form method="Post" action="{% url 'posts:create' %}"  enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
	<input class="btn btn-primary" type="submit" value=" Create Post" class="btn btn-success">
	
	</form>
	</div>
</div>

{% endblock content %}

posts/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}

{% block title %}
{{title}}
{% endblock title %}


{% block content %}
   
    <div class="row">
    
        <div class="col-sm-6 col-sm-offset-3">
            <div class="thumbnail">
            {% if object.image %}
            <img src="{{object.image.url}}" class="img-responsive">

            {% endif %}
                <div class="caption">

                    <h3>{{object.title}}<small>{{object.publish|timesince}} ago </small></h3>
                    <p>{{object.content|linebreaks}}</p>


                    Author: {{object.author.username}}

                    <p>
                    <br>

             <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
                share on Facebook</a>

                <br>
             
                <a href="https://twitter.com/home?status={{instance.content|urlify|truncatechars:50}}%20{{request.build_absolute_uri}}">
                    share on Twitter
                    </a>

                <br>
                <br>
                <button class="btn" onclick="ajax_like()">
                <span id="like_count">{{like_count}}</span>
                <span id ="heart "class="glyphicon glyphicon-heart {% if liked %}text-danger{% endif %}"aria-hidden="true"></span>
                </button>
                {# {% include "django_comments.html" %} #}

<div class="fb-likev col-sm-8 col-sm-offset-2" data-href="{{request.build_absolute_uri}}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>
<div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div>
            <br>



            <a href="{% url 'posts:list' %}" class = "btn btn-warning">Go Back To List</a>

            {# <a href="{{object.get_absolute_url}}" class="btn btn-primary">View</a> #}
            {# <a href="{% url 'posts:update' slug=0 %}" class="btn btn-success">Edit</a> #}
            {# <a href="{% url 'posts:delete' slug=0 %}" class="btn btn-danger">Delete</a></p> #}


           
            		


                </div>
            </div>
        </div>




<script>
    function ajax_like()
    {
        console.log("Like/Unlike clicked!")
        $.ajax({

            type: 'GET' ,
            url: '{% url "posts:like_button" post_id=object.id %}' ,                                                   
            error: function(){
                console.log("noob")

            },
            success: function (data) { 

                $("#like_count").text(data.like_count)

                if(data.action==="like"){

                    $("#heart").addClass("text-danger");

                }else{

                    $("#heart").removeClass("text-danger");
                }

            },



        });

    }
</script>

            	
            	

{% endblock content %}

posts/templates/post_list.html
{% extends "base.html" %}

{% block content %}
<div class="row">





    {% for object in post_list %}
        <div class="col-sm-6" style="top:20px">

            <div class="">
            {% if object.image %}
            <img src="{{object.image.url}}" class="img img-responsive thumbnail list-images">

            {% endif %}
          
                <div class="caption">
                    <h3>{{object.title}}</a><small> {{object.publish|timesince }} ago</small></h3>
                    {# <p>{{object.content|linebreaks|truncatechars:100}}</p> #}
                    {% if object.draft %}<h4>Draft</h4>{% endif %}
                    {% if object.publish > today %} <h4>Future Blog Post</h4>{% endif %}

            <p> {{object.content|linebreaks|truncatechars:10}}</p>
            <p>

            <a href="{{object.get_absolute_url}}" class="btn btn-primary">View</a>
            {% if requset.user.is_staff or request.user.is_superuser %}
            <a href="{% url 'posts:update' slug=object.slug %}" class="btn btn-success">Edit</a> 
            <a href="{% url 'posts:delete' slug=object.slug %}" class="btn btn-danger">Delete</a>




            

             {% endif %}
            </p>
                </div>
            </div>
        </div>


    {% endfor %}

    </div>
    <br>
    <div class="pagination">
        <span class="step-links">
            {% if post_list.has_previous %}
                <a href="?page={{ post_list.previous_page_number }}&q={{request.GET.q}}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.

            </span>

            {% if post_list.has_next %}
                <a href="?page={{ post_list.next_page_number }}">next</a>
            {% endif %}
        </span>

    </div>


{% endblock content %}

posts/templates/post_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{{title}}
{% endblock title %}


{% block content %}
  <div class="row">
	<div class="col-sm-6 col-sm-offset-3">
	
	<form method="Post" action="{% url 'posts:update' slug=post_object.slug %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value=" Update Post" class="btn btn-success">
	
	</form>
		</div>
</div>


{% endblock content %}

posts/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Signup{% endblock title %}


{% block content %}
  <div class="row">
	<div class="col-sm-6 col-sm-offset-3">
	
	<form method="Post" action="{% url 'posts:signup' %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value=" Update Post" class="btn btn-success">
	
	</form>
		</div>
</div>


{% endblock content %}

posts/templates/whatever.html
<!DOCTYPE html>
<html>
<head>
	<title>Create Page</title>
</head>
<body>
<h1>{{user}}</h1>

<ol>
<li>{{instance.id}}</li>
<li>{{instance.title}}</li>
<li>{{instance.content}}</li>

</ol>
</body>
</html>